export const PAGE_SIZE = 20;

export const CATEGORIES = [
  { id: "tech", name: "Technology & IT", count: 124 },
  { id: "finance", name: "Finance & Banking", count: 83 },
  { id: "health", name: "Healthcare & Medical", count: 62 },
  { id: "edu", name: "Education & Training", count: 97 },
  { id: "retail", name: "Retail & Shopping", count: 210 },
  { id: "const", name: "Construction", count: 74 },
  { id: "food", name: "Food & Dining", count: 188 },
  { id: "travel", name: "Travel & Tourism", count: 56 },
  { id: "mfg", name: "Manufacturing", count: 48 },
  { id: "auto", name: "Automotive", count: 39 },
  { id: "media", name: "Media & Advertising", count: 31 },
  { id: "ngo", name: "NGO & Non-Profit", count: 27 },
  { id: "legal", name: "Legal & Consulting", count: 44 },
  { id: "agri", name: "Agriculture", count: 52 },
  { id: "energy", name: "Energy & Utilities", count: 19 },
];

export const CITIES = [
  "Banepa",
  "Bhaktapur",
  "Bharatpur",
  "Biratnagar",
  "Birgunj",
  "Butwal",
  "Damak",
  "Dharan",
  "Dhangadhi",
  "Gorkha",
  "Hetauda",
  "Itahari",
  "Janakpur",
  "Kathmandu",
  "Kirtipur",
  "Lalitpur",
  "Lekhnath",
  "Nepalgunj",
  "Pokhara",
  "Rajbiraj",
  "Siddharthanagar",
  "Sundhara",
  "Tansen",
  "Tulsipur",
  "Waling",
];

export const DISTRICTS = [
  "Achham",
  "Arghakhanchi",
  "Baglung",
  "Baitadi",
  "Bajhang",
  "Bajura",
  "Banke",
  "Bara",
  "Bardiya",
  "Bhaktapur",
  "Bhojpur",
  "Chitwan",
  "Dadeldhura",
  "Dailekh",
  "Dang",
  "Darchula",
  "Dhading",
  "Dhankuta",
  "Dhanusa",
  "Dholkha",
  "Dolpa",
  "Doti",
  "Gorkha",
  "Gulmi",
  "Humla",
  "Ilam",
  "Jajarkot",
  "Jhapa",
  "Jumla",
  "Kailali",
  "Kalikot",
  "Kanchanpur",
  "Kapilvastu",
  "Kaski",
  "Kathmandu",
  "Kavrepalanchok",
  "Khotang",
  "Lalitpur",
  "Lamjung",
  "Mahottari",
  "Makwanpur",
  "Manang",
  "Morang",
  "Mugu",
  "Mustang",
  "Myagdi",
  "Nawalpur",
  "Nuwakot",
  "Okhaldhunga",
  "Palpa",
  "Panchthar",
  "Parasi",
  "Parbat",
  "Parsa",
  "Pyuthan",
  "Ramechhap",
  "Rasuwa",
  "Rautahat",
  "Rolpa",
  "Rukum (East)",
  "Rukum (West)",
  "Rupandehi",
  "Salyan",
  "Sankhuwasabha",
  "Saptari",
  "Sarlahi",
  "Sindhuli",
  "Sindhupalchok",
  "Siraha",
  "Solukhumbu",
  "Sunsari",
  "Surkhet",
  "Syangja",
  "Tanahun",
  "Taplejung",
  "Terhathum",
  "Udayapur",
];

export const COMPANY_DATA = [
  {
    id: 1,
    name: "TechSphere Solutions",
    cat: "tech",
    city: "Kathmandu",
    district: "Kathmandu",
    logo: "TS",
    lc: "lg-1",
    badge: "featured",
    rating: 4.9,
    year: 2014,
    desc: "Custom software development, cloud solutions, and digital transformation services for enterprises.",
    tags: ["Software", "Cloud", "ERP"],
  },
  {
    id: 2,
    name: "GoldFinance Group",
    cat: "finance",
    city: "Lalitpur",
    district: "Lalitpur",
    logo: "GF",
    lc: "lg-2",
    badge: "featured",
    rating: 4.8,
    year: 2008,
    desc: "Comprehensive financial services including loans, investment consulting, and wealth management.",
    tags: ["Loans", "Investment", "Banking"],
  },
  {
    id: 3,
    name: "HealthCare Plus",
    cat: "health",
    city: "Pokhara",
    district: "Kaski",
    logo: "HC",
    lc: "lg-3",
    badge: "new",
    rating: 4.6,
    year: 2021,
    desc: "Modern medical facilities with specialist doctors, diagnostics, and telemedicine services.",
    tags: ["Hospital", "Diagnostics", "Tele-med"],
  },
  {
    id: 4,
    name: "EduAcademy Nepal",
    cat: "edu",
    city: "Kathmandu",
    district: "Kathmandu",
    logo: "EA",
    lc: "lg-4",
    badge: "featured",
    rating: 4.9,
    year: 2011,
    desc: "Professional certification courses, skill development programs, and vocational training centers.",
    tags: ["Training", "Certification", "Skills"],
  },
  {
    id: 5,
    name: "BuildMasters Co.",
    cat: "const",
    city: "Bhaktapur",
    district: "Bhaktapur",
    logo: "BM",
    lc: "lg-5",
    badge: "new",
    rating: 4.5,
    year: 2019,
    desc: "Residential and commercial construction, interior design, and property development firm.",
    tags: ["Construction", "Interior", "Real Estate"],
  },
  {
    id: 6,
    name: "TrekTours Nepal",
    cat: "travel",
    city: "Pokhara",
    district: "Kaski",
    logo: "TT",
    lc: "lg-6",
    badge: "featured",
    rating: 5.0,
    year: 2007,
    desc: "Award-winning trekking, adventure tours, and customised travel packages across the Himalayas.",
    tags: ["Trekking", "Adventure", "Tours"],
  },
  {
    id: 7,
    name: "MegaMart Retail",
    cat: "retail",
    city: "Kathmandu",
    district: "Kathmandu",
    logo: "MR",
    lc: "lg-7",
    badge: "verified",
    rating: 4.4,
    year: 2015,
    desc: "Wide range of consumer goods, electronics, fashion and household products at affordable prices.",
    tags: ["Supermarket", "Electronics", "Fashion"],
  },
  {
    id: 8,
    name: "AutoZone Nepal",
    cat: "auto",
    city: "Lalitpur",
    district: "Lalitpur",
    logo: "AZ",
    lc: "lg-8",
    badge: "verified",
    rating: 4.3,
    year: 2012,
    desc: "Authorised dealer for passenger vehicles, SUVs, spare parts, and service center operations.",
    tags: ["Cars", "Spare Parts", "Service"],
  },
  {
    id: 9,
    name: "ClearSky Media",
    cat: "media",
    city: "Kathmandu",
    district: "Kathmandu",
    logo: "CM",
    lc: "lg-1",
    badge: "new",
    rating: 4.2,
    year: 2020,
    desc: "Creative advertising agency offering branding, digital marketing, and media production services.",
    tags: ["Branding", "Digital", "Advertising"],
  },
  {
    id: 10,
    name: "Green Harvest Agro",
    cat: "agri",
    city: "Bharatpur",
    district: "Chitwan",
    logo: "GH",
    lc: "lg-7",
    badge: "verified",
    rating: 4.6,
    year: 2010,
    desc: "Organic farming, agri-products export, and farmer cooperative support programs nationwide.",
    tags: ["Organic", "Export", "Farming"],
  },
  {
    id: 11,
    name: "PowerGrid Energy",
    cat: "energy",
    city: "Birgunj",
    district: "Parsa",
    logo: "PE",
    lc: "lg-5",
    badge: "featured",
    rating: 4.7,
    year: 2009,
    desc: "Renewable energy solutions, solar installations, and power distribution across Nepal.",
    tags: ["Solar", "Renewable", "Power"],
  },
  {
    id: 12,
    name: "LexCorp Legal",
    cat: "legal",
    city: "Kathmandu",
    district: "Kathmandu",
    logo: "LC",
    lc: "lg-4",
    badge: "verified",
    rating: 4.8,
    year: 2006,
    desc: "Corporate law, intellectual property, tax consulting, and dispute resolution services.",
    tags: ["Corporate Law", "IP", "Tax"],
  },
  {
    id: 13,
    name: "Savour Kitchen",
    cat: "food",
    city: "Pokhara",
    district: "Kaski",
    logo: "SK",
    lc: "lg-3",
    badge: "featured",
    rating: 4.9,
    year: 2018,
    desc: "Multi-cuisine restaurant chain offering authentic Nepali, Indian, and continental dining experiences.",
    tags: ["Restaurant", "Multi-cuisine", "Catering"],
  },
  {
    id: 14,
    name: "HopeNGO Foundation",
    cat: "ngo",
    city: "Kathmandu",
    district: "Kathmandu",
    logo: "HN",
    lc: "lg-6",
    badge: "verified",
    rating: 4.5,
    year: 2013,
    desc: "Non-profit working in education, livelihood, and disaster relief programs across rural Nepal.",
    tags: ["Education", "Relief", "Livelihood"],
  },
  {
    id: 15,
    name: "NepalMfg Industries",
    cat: "mfg",
    city: "Biratnagar",
    district: "Morang",
    logo: "NI",
    lc: "lg-8",
    badge: "verified",
    rating: 4.3,
    year: 2003,
    desc: "Large-scale manufacturing of textiles, garments, and industrial goods with export capability.",
    tags: ["Textiles", "Garments", "Export"],
  },
  {
    id: 16,
    name: "SwiftTech IT",
    cat: "tech",
    city: "Lalitpur",
    district: "Lalitpur",
    logo: "ST",
    lc: "lg-4",
    badge: "new",
    rating: 4.4,
    year: 2022,
    desc: "IT infrastructure, networking, cybersecurity services and managed support for businesses.",
    tags: ["Networking", "Cybersecurity", "IT Support"],
  },
  {
    id: 17,
    name: "Himalayan Finance",
    cat: "finance",
    city: "Pokhara",
    district: "Kaski",
    logo: "HF",
    lc: "lg-2",
    badge: "verified",
    rating: 4.5,
    year: 2016,
    desc: "Microfinance, SME loans, and rural banking services to underserved communities across Nepal.",
    tags: ["Microfinance", "SME", "Rural Banking"],
  },
  {
    id: 18,
    name: "CareHospital Pvt.",
    cat: "health",
    city: "Kathmandu",
    district: "Kathmandu",
    logo: "CH",
    lc: "lg-1",
    badge: "featured",
    rating: 4.7,
    year: 2005,
    desc: "200-bed multi-specialty hospital with advanced diagnostic and surgical facilities.",
    tags: ["Hospital", "Surgery", "Diagnostics"],
  },
  {
    id: 19,
    name: "BrightMinds School",
    cat: "edu",
    city: "Bhaktapur",
    district: "Bhaktapur",
    logo: "BS",
    lc: "lg-6",
    badge: "verified",
    rating: 4.6,
    year: 2008,
    desc: "K-12 international curriculum school focused on holistic child development and academic excellence.",
    tags: ["K-12", "International", "Curriculum"],
  },
  {
    id: 20,
    name: "FreshBite Restaurants",
    cat: "food",
    city: "Kathmandu",
    district: "Kathmandu",
    logo: "FB",
    lc: "lg-3",
    badge: "new",
    rating: 4.4,
    year: 2021,
    desc: "Fast-casual dining chain with healthy menu options, delivery, and cloud kitchen operations.",
    tags: ["Fast-casual", "Healthy", "Delivery"],
  },
  {
    id: 21,
    name: "VoyageNepal Tours",
    cat: "travel",
    city: "Kathmandu",
    district: "Kathmandu",
    logo: "VN",
    lc: "lg-7",
    badge: "verified",
    rating: 4.5,
    year: 2014,
    desc: "Cultural tours, heritage walks, and international travel packages designed for all budgets.",
    tags: ["Cultural", "Heritage", "International"],
  },
  {
    id: 22,
    name: "StyleHub Fashion",
    cat: "retail",
    city: "Pokhara",
    district: "Kaski",
    logo: "SH",
    lc: "lg-8",
    badge: "new",
    rating: 4.2,
    year: 2023,
    desc: "Contemporary fashion boutique offering local and imported apparel, accessories, and footwear.",
    tags: ["Fashion", "Apparel", "Boutique"],
  },
  {
    id: 23,
    name: "MotorWorld Pvt.",
    cat: "auto",
    city: "Biratnagar",
    district: "Morang",
    logo: "MW",
    lc: "lg-5",
    badge: "verified",
    rating: 4.3,
    year: 2011,
    desc: "Motorcycle dealership, repair workshop, and accessories shop serving eastern Nepal.",
    tags: ["Motorcycles", "Repair", "Accessories"],
  },
  {
    id: 24,
    name: "PixelForge Agency",
    cat: "media",
    city: "Lalitpur",
    district: "Lalitpur",
    logo: "PF",
    lc: "lg-2",
    badge: "featured",
    rating: 4.7,
    year: 2017,
    desc: "Full-service digital agency: web design, SEO, social media management, and video production.",
    tags: ["Web Design", "SEO", "Video"],
  },
  {
    id: 25,
    name: "RiceField Agro Pvt.",
    cat: "agri",
    city: "Birgunj",
    district: "Parsa",
    logo: "RA",
    lc: "lg-7",
    badge: "verified",
    rating: 4.4,
    year: 2007,
    desc: "Large-scale paddy cultivation, rice milling, and agricultural input supply to farmers.",
    tags: ["Rice", "Milling", "Input Supply"],
  },
  {
    id: 26,
    name: "SolarSpark Nepal",
    cat: "energy",
    city: "Kathmandu",
    district: "Kathmandu",
    logo: "SS",
    lc: "lg-3",
    badge: "new",
    rating: 4.5,
    year: 2019,
    desc: "Affordable solar home systems, commercial installations, and off-grid solutions for rural areas.",
    tags: ["Solar", "Off-grid", "Home Systems"],
  },
  {
    id: 27,
    name: "TrustLex Consultants",
    cat: "legal",
    city: "Pokhara",
    district: "Kaski",
    logo: "TL",
    lc: "lg-4",
    badge: "verified",
    rating: 4.4,
    year: 2015,
    desc: "Legal advisory, business registration, compliance, and intellectual property services.",
    tags: ["Advisory", "Compliance", "Registration"],
  },
  {
    id: 28,
    name: "MountainBrew Café",
    cat: "food",
    city: "Bhaktapur",
    district: "Bhaktapur",
    logo: "MB",
    lc: "lg-1",
    badge: "verified",
    rating: 4.8,
    year: 2016,
    desc: "Specialty coffee, artisan pastries, and co-working café spaces in a heritage setting.",
    tags: ["Coffee", "Artisan", "Co-working"],
  },
  {
    id: 29,
    name: "NexaCode Systems",
    cat: "tech",
    city: "Kathmandu",
    district: "Kathmandu",
    logo: "NC",
    lc: "lg-6",
    badge: "new",
    rating: 4.3,
    year: 2023,
    desc: "App development, API integration, and AI-powered analytics solutions for startups and enterprises.",
    tags: ["App Dev", "AI", "Analytics"],
  },
  {
    id: 30,
    name: "SafeGuard Insurance",
    cat: "finance",
    city: "Lalitpur",
    district: "Lalitpur",
    logo: "SG",
    lc: "lg-5",
    badge: "featured",
    rating: 4.6,
    year: 2004,
    desc: "Life, health, vehicle, and property insurance with easy claims and nationwide branch network.",
    tags: ["Life Insurance", "Health", "Vehicle"],
  },
  {
    id: 31,
    name: "WellnessFirst Clinic",
    cat: "health",
    city: "Pokhara",
    district: "Kaski",
    logo: "WF",
    lc: "lg-7",
    badge: "new",
    rating: 4.4,
    year: 2020,
    desc: "Wellness centre offering physiotherapy, nutrition counselling, and preventive health programs.",
    tags: ["Physiotherapy", "Nutrition", "Wellness"],
  },
  {
    id: 32,
    name: "CodeCamp Academy",
    cat: "edu",
    city: "Kathmandu",
    district: "Kathmandu",
    logo: "CA",
    lc: "lg-3",
    badge: "verified",
    rating: 4.7,
    year: 2018,
    desc: "Coding bootcamps, UI/UX design, data science, and digital marketing courses for youth.",
    tags: ["Coding", "UI/UX", "Data Science"],
  },
  {
    id: 33,
    name: "UrbanNest Builders",
    cat: "const",
    city: "Lalitpur",
    district: "Lalitpur",
    logo: "UB",
    lc: "lg-8",
    badge: "featured",
    rating: 4.6,
    year: 2012,
    desc: "Premium residential and commercial construction projects with modern architecture and quality finishes.",
    tags: ["Residential", "Commercial", "Architecture"],
  },
  {
    id: 34,
    name: "TrailBlazer Adventures",
    cat: "travel",
    city: "Biratnagar",
    district: "Morang",
    logo: "TA",
    lc: "lg-2",
    badge: "new",
    rating: 4.3,
    year: 2022,
    desc: "Eco-tourism, jungle safaris, bird watching, and adventure sports packages in eastern Nepal.",
    tags: ["Eco-tourism", "Safari", "Bird Watching"],
  },
  {
    id: 35,
    name: "DailyMart Superstore",
    cat: "retail",
    city: "Birgunj",
    district: "Parsa",
    logo: "DS",
    lc: "lg-1",
    badge: "verified",
    rating: 4.2,
    year: 2017,
    desc: "One-stop shopping destination for groceries, electronics, clothing, and household essentials.",
    tags: ["Groceries", "Electronics", "Household"],
  },
  {
    id: 36,
    name: "PrideAuto Service",
    cat: "auto",
    city: "Kathmandu",
    district: "Kathmandu",
    logo: "PA",
    lc: "lg-6",
    badge: "verified",
    rating: 4.5,
    year: 2009,
    desc: "Authorised multi-brand car service center, genuine spare parts, and body repair shop.",
    tags: ["Service Center", "Spare Parts", "Body Repair"],
  },
  {
    id: 37,
    name: "VisionMedia Nepal",
    cat: "media",
    city: "Kathmandu",
    district: "Kathmandu",
    logo: "VM",
    lc: "lg-4",
    badge: "verified",
    rating: 4.4,
    year: 2013,
    desc: "Television production, documentary filmmaking, and news media services for broadcast and digital.",
    tags: ["TV Production", "Documentary", "News"],
  },
  {
    id: 38,
    name: "FarmFresh Cooperative",
    cat: "agri",
    city: "Bharatpur",
    district: "Chitwan",
    logo: "FF",
    lc: "lg-7",
    badge: "new",
    rating: 4.5,
    year: 2019,
    desc: "Farmers cooperative for fresh produce aggregation, cold storage, and direct market linkages.",
    tags: ["Cooperative", "Cold Storage", "Produce"],
  },
  {
    id: 39,
    name: "EcoWatt Energy",
    cat: "energy",
    city: "Pokhara",
    district: "Kaski",
    logo: "EW",
    lc: "lg-3",
    badge: "featured",
    rating: 4.6,
    year: 2015,
    desc: "Hydro-micro energy projects, biogas solutions, and energy auditing for commercial clients.",
    tags: ["Hydro", "Biogas", "Energy Audit"],
  },
  {
    id: 40,
    name: "LawBridge Associates",
    cat: "legal",
    city: "Kathmandu",
    district: "Kathmandu",
    logo: "LB",
    lc: "lg-5",
    badge: "verified",
    rating: 4.7,
    year: 2010,
    desc: "Employment law, civil litigation, and corporate governance advisory for businesses and individuals.",
    tags: ["Employment Law", "Litigation", "Corporate"],
  },
  {
    id: 41,
    name: "CrunchBox Bakery",
    cat: "food",
    city: "Lalitpur",
    district: "Lalitpur",
    logo: "CB",
    lc: "lg-8",
    badge: "new",
    rating: 4.3,
    year: 2022,
    desc: "Artisan breads, custom cakes, and wholesale bakery supplies for hotels and restaurants.",
    tags: ["Bakery", "Custom Cakes", "Wholesale"],
  },
  {
    id: 42,
    name: "DataBridge Solutions",
    cat: "tech",
    city: "Pokhara",
    district: "Kaski",
    logo: "DB",
    lc: "lg-2",
    badge: "featured",
    rating: 4.5,
    year: 2016,
    desc: "Business intelligence, data warehousing, and cloud migration services for growing enterprises.",
    tags: ["BI", "Data Warehouse", "Cloud"],
  },
  {
    id: 43,
    name: "ApexBuild Contractors",
    cat: "const",
    city: "Kathmandu",
    district: "Kathmandu",
    logo: "AB",
    lc: "lg-6",
    badge: "verified",
    rating: 4.4,
    year: 2007,
    desc: "Infrastructure projects, road construction, and government contract work across Nepal.",
    tags: ["Infrastructure", "Roads", "Government"],
  },
  {
    id: 44,
    name: "PeakVenture Travel",
    cat: "travel",
    city: "Pokhara",
    district: "Kaski",
    logo: "PV",
    lc: "lg-1",
    badge: "verified",
    rating: 4.6,
    year: 2010,
    desc: "Luxury trekking expeditions, helicopter tours, and customised Himalayan adventure itineraries.",
    tags: ["Luxury", "Helicopter", "Expedition"],
  },
  {
    id: 45,
    name: "TextilePlus Mfg.",
    cat: "mfg",
    city: "Biratnagar",
    district: "Morang",
    logo: "TP",
    lc: "lg-4",
    badge: "featured",
    rating: 4.3,
    year: 2001,
    desc: "Garment and textile manufacturing with export quality standards and in-house design studio.",
    tags: ["Garments", "Textile", "Export"],
  },
];
